parameters:
#    sonia_page.example.class: Sonia\PageBundle\Example

services:
#    sonia_page.example:
#        class: %sonia_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
