parameters:
#    andrei_personal_page.example.class: Andrei\PersonalPageBundle\Example

services:
#    andrei_personal_page.example:
#        class: %andrei_personal_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
